FUNC_PATH="~/.funcs"
cat "${FUNC_PATH}/sourceAll.sh"
source "${FUNC_PATH}/funcs/gitAC.sh"
source "${FUNC_PATH}/funcs/gitCoFet.sh"
source "${FUNC_PATH}/funcs/gitCoFetE.sh"
source "${FUNC_PATH}/funcs/printf.sh"
source "${FUNC_PATH}/funcs/srcZsh.sh"
